version: 2
jobs:
  build:
    docker:
      - image: cppchriscpp/cc65-node:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "62:d1:f8:4c:c4:bd:64:69:ca:6f:56:05:12:31:79:8d"
      - run:
          name: Move tools folder to expected location
          command: cp -rf /tools .
      - run:
          name: "Npm installs"
          command: "cd tools/tmx2c/src && npm install && cd ../../../tools/sprite_def2img/src && npm install && cd ../../../tools/chr2img/src && npm install"
      - run:
          name: Build the game itself
          command: make
      - store_artifacts:
          path: ./rom
      - run: 
          name: Upload to version number in s3
          command: aws s3 cp --region us-east-1 ./rom/ld44.nes s3://cpprograms-nes-games-https/ld44/$CIRCLE_BRANCH/ld44.$CIRCLE_BUILD_NUM.nes --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - run: 
          name: Replace "latest" rom file in s3
          command: aws s3 cp --region us-east-1 ./rom/ld44.nes s3://cpprograms-nes-games-https/ld44/$CIRCLE_BRANCH/ld44.latest.nes --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers

workflows:
  version: 2
  build:
    jobs: 
      - build
